In [1]:
import os
#os.environ['CUDA_VISIBLE_DEVICES'] = '2'
import random 
import gym
from matplotlib import pylab
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.losses import MSE
from tensorflow.keras.optimizers import SGD, Adam, RMSprop
import tensorflow.keras.initializers as init

In [1]:
####### Random Model ##########
import gym
env = gym.make('CartPole-v1')
observation = env.reset()
for _ in range(1000):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)
  print(observation, observation.shape,reward,done)

  if done:
    observation = env.reset()
env.close()


[-0.01984831  0.21217068 -0.00872496 -0.31607453] (4,) 1.0 False
[-0.0156049   0.01717409 -0.01504645 -0.02615588] (4,) 1.0 False
[-0.01526142  0.21250855 -0.01556957 -0.3235479 ] (4,) 1.0 False
[-0.01101125  0.4078487  -0.02204052 -0.62109988] (4,) 1.0 False
[-0.00285427  0.6032714  -0.03446252 -0.92064212] (4,) 1.0 False
[ 0.00921115  0.40863172 -0.05287536 -0.63898593] (4,) 1.0 False
[ 0.01738379  0.21428533 -0.06565508 -0.36341189] (4,) 1.0 False
[ 0.0216695   0.41027599 -0.07292332 -0.6760532 ] (4,) 1.0 False
[ 0.02987502  0.21623904 -0.08644438 -0.40719178] (4,) 1.0 False
[ 0.0341998   0.41247357 -0.09458822 -0.72582748] (4,) 1.0 False
[ 0.04244927  0.60876731 -0.10910477 -1.04671939] (4,) 1.0 False
[ 0.05462461  0.80515483 -0.13003916 -1.37156228] (4,) 1.0 False
[ 0.07072771  0.61187669 -0.1574704  -1.12221675] (4,) 1.0 False
[ 0.08296524  0.41913011 -0.17991474 -0.88277932] (4,) 1.0 False
[ 0.09134785  0.22684755 -0.19757032 -0.65162098] (4,) 1.0 False
[ 0.0958848   0.42409241 

[-0.13999359 -1.16788435  0.16649734  1.99731021] (4,) 1.0 False
[-0.16335127 -1.36431046  0.20644354  2.33659928] (4,) 1.0 False
[-0.19063748 -1.56061435  0.25317553  2.68506687] (4,) 1.0 True
[ 0.01340121 -0.15059628 -0.02772139  0.29981487] (4,) 1.0 False
[ 0.01038928  0.04490962 -0.02172509 -0.00148034] (4,) 1.0 False
[ 0.01128748 -0.14989414 -0.0217547   0.28426966] (4,) 1.0 False
[ 0.00828959  0.04553123 -0.0160693  -0.0151944 ] (4,) 1.0 False
[ 0.00920022 -0.14935663 -0.01637319  0.27237546] (4,) 1.0 False
[ 0.00621308 -0.34424117 -0.01092568  0.55984959] (4,) 1.0 False
[-6.71738588e-04 -5.39208078e-01  2.71308979e-04  8.49070415e-01] (4,) 1.0 False
[-0.0114559  -0.34408983  0.01725272  0.55647282] (4,) 1.0 False
[-0.0183377  -0.53944969  0.02838217  0.85454105] (4,) 1.0 False
[-0.02912669 -0.34472582  0.04547299  0.57091612] (4,) 1.0 False
[-0.03602121 -0.15027007  0.05689132  0.29289846] (4,) 1.0 False
[-0.03902661 -0.34615506  0.06274929  0.6029676 ] (4,) 1.0 False
[-0.045949

[ 0.10648478  0.81646382 -0.04035888 -1.0965505 ] (4,) 1.0 False
[ 0.12281405  1.01209332 -0.06228989 -1.40161808] (4,) 1.0 False
[ 0.14305592  0.81779817 -0.09032225 -1.12904196] (4,) 1.0 False
[ 0.15941188  0.62396775 -0.11290309 -0.86600015] (4,) 1.0 False
[ 0.17189124  0.43054848 -0.13022309 -0.61084146] (4,) 1.0 False
[ 0.18050221  0.62722704 -0.14243992 -0.94153884] (4,) 1.0 False
[ 0.19304675  0.43428209 -0.1612707  -0.69678836] (4,) 1.0 False
[ 0.20173239  0.24172033 -0.17520647 -0.45890206] (4,) 1.0 False
[ 0.2065668   0.04945164 -0.18438451 -0.22616187] (4,) 1.0 False
[ 0.20755583 -0.14262222 -0.18890775  0.00316284] (4,) 1.0 False
[ 0.20470339 -0.3346036  -0.18884449  0.23080272] (4,) 1.0 False
[ 0.19801131 -0.13735564 -0.18422844 -0.11500002] (4,) 1.0 False
[ 0.1952642   0.05986241 -0.18652844 -0.45967838] (4,) 1.0 False
[ 0.19646145  0.25706336 -0.195722   -0.80487072] (4,) 1.0 False
[ 0.20160272  0.45425252 -0.21181942 -1.1521828 ] (4,) 1.0 True
[ 0.03818292 -0.18688071  

[ 0.09430879  0.38015113 -0.22583003 -1.25722121] (4,) 1.0 True
[ 0.03572093 -0.23420865 -0.03564096  0.27844229] (4,) 1.0 False
[ 0.03103675 -0.03859686 -0.03007211 -0.02526528] (4,) 1.0 False
[ 0.03026481 -0.23327493 -0.03057742  0.25777993] (4,) 1.0 False
[ 0.02559932 -0.4279473  -0.02542182  0.54066362] (4,) 1.0 False
[ 0.01704037 -0.62270287 -0.01460855  0.82522937] (4,) 1.0 False
[ 0.00458631 -0.817622    0.00189604  1.11328211] (4,) 1.0 False
[-0.01176613 -0.622525    0.02416168  0.82119457] (4,) 1.0 False
[-0.02421663 -0.42774185  0.04058557  0.53620797] (4,) 1.0 False
[-0.03277146 -0.23321337  0.05130973  0.25658442] (4,) 1.0 False
[-0.03743573 -0.0388601   0.05644142 -0.01948338] (4,) 1.0 False
[-0.03821293 -0.23474415  0.05605175  0.29045978] (4,) 1.0 False
[-0.04290782 -0.43061869  0.06186095  0.60028075] (4,) 1.0 False
[-0.05152019 -0.62654903  0.07386656  0.91178963] (4,) 1.0 False
[-0.06405117 -0.82258851  0.09210236  1.226744  ] (4,) 1.0 False
[-0.08050294 -0.62876491  

[ 0.05018508  1.00131477 -0.05460724 -1.46562439] (4,) 1.0 False
[ 0.07021138  1.19706126 -0.08391973 -1.77485301] (4,) 1.0 False
[ 0.0941526   1.00297937 -0.11941679 -1.50939814] (4,) 1.0 False
[ 0.11421219  0.80948993 -0.14960475 -1.2562561 ] (4,) 1.0 False
[ 0.13040199  0.61656577 -0.17472987 -1.0139222 ] (4,) 1.0 False
[ 0.1427333   0.813533   -0.19500832 -1.35598395] (4,) 1.0 False
[ 0.15900396  1.01049255 -0.222128   -1.7027933 ] (4,) 1.0 True
[ 0.02653145 -0.17307842  0.04036537  0.28712796] (4,) 1.0 False
[ 0.02306988 -0.36875207  0.04610793  0.59226356] (4,) 1.0 False
[ 0.01569484 -0.17430489  0.0579532   0.3144537 ] (4,) 1.0 False
[0.01220874 0.01994569 0.06424227 0.0405957 ] (4,) 1.0 False
[ 0.01260766  0.2140904   0.06505418 -0.2311464 ] (4,) 1.0 False
[ 0.01688946  0.40822537  0.06043126 -0.50262043] (4,) 1.0 False
[ 0.02505397  0.21230602  0.05037885 -0.19152189] (4,) 1.0 False
[ 0.02930009  0.40667243  0.04654841 -0.46789648] (4,) 1.0 False
[ 0.03743354  0.21092482  0.03

[ 0.02874625 -0.1971594  -0.01910108  0.21514271] (4,) 1.0 False
[ 0.02480306 -0.39200314 -0.01479822  0.50173964] (4,) 1.0 False
[ 0.016963   -0.58691341 -0.00476343  0.7897225 ] (4,) 1.0 False
[ 0.00522473 -0.39172637  0.01103102  0.49554482] (4,) 1.0 False
[-0.00260979 -0.58700213  0.02094192  0.79168369] (4,) 1.0 False
[-0.01434984 -0.78240525  0.03677559  1.09088058] (4,) 1.0 False
[-0.02999794 -0.97799211  0.0585932   1.39487209] (4,) 1.0 False
[-0.04955778 -0.78364616  0.08649064  1.12106998] (4,) 1.0 False
[-0.06523071 -0.97978932  0.10891204  1.43958151] (4,) 1.0 False
[-0.08482649 -1.17607145  0.13770367  1.76421711] (4,) 1.0 False
[-0.10834792 -0.98274922  0.17298802  1.51733585] (4,) 1.0 False
[-0.12800291 -1.17948974  0.20333473  1.85864726] (4,) 1.0 False
[-0.1515927  -0.98709766  0.24050768  1.63537378] (4,) 1.0 True
[-0.01020131 -0.21769921  0.02936926  0.26005002] (4,) 1.0 False
[-0.01455529 -0.41322784  0.03457026  0.56184981] (4,) 1.0 False
[-0.02281985 -0.21860765  

[-0.00280814 -0.39495006  0.01060195  0.50142391] (4,) 1.0 False
[-0.01070714 -0.19997915  0.02063042  0.21210089] (4,) 1.0 False
[-0.01470672 -0.00515814  0.02487244 -0.07400351] (4,) 1.0 False
[-0.01480989  0.18959857  0.02339237 -0.35873647] (4,) 1.0 False
[-0.01101792  0.3843803   0.01621764 -0.64395241] (4,) 1.0 False
[-0.00333031  0.57927252  0.00333859 -0.93148451] (4,) 1.0 False
[ 0.00825514  0.38410567 -0.0152911  -0.63775433] (4,) 1.0 False
[ 0.01593725  0.18920025 -0.02804618 -0.34992578] (4,) 1.0 False
[ 0.01972126 -0.00551184 -0.0350447  -0.06621701] (4,) 1.0 False
[ 0.01961102  0.19009457 -0.03636904 -0.36974751] (4,) 1.0 False
[ 0.02341291 -0.00449228 -0.04376399 -0.08875039] (4,) 1.0 False
[ 0.02332307  0.19122877 -0.045539   -0.39491335] (4,) 1.0 False
[ 0.02714764 -0.00321843 -0.05343726 -0.11692878] (4,) 1.0 False
[ 0.02708327  0.19262683 -0.05577584 -0.42598042] (4,) 1.0 False
[ 0.03093581 -0.00166256 -0.06429545 -0.15138913] (4,) 1.0 False
[ 0.03090256  0.19431831 

[-0.0235924   0.1735836  -0.04104341 -0.31237316] (4,) 1.0 False
[-0.02012073  0.36926551 -0.04729087 -0.61771219] (4,) 1.0 False
[-0.01273542  0.17483496 -0.05964511 -0.34029077] (4,) 1.0 False
[-0.00923872 -0.01938986 -0.06645093 -0.06699688] (4,) 1.0 False
[-0.00962652  0.17661877 -0.06779087 -0.37988312] (4,) 1.0 False
[-0.00609414  0.37263461 -0.07538853 -0.69314679] (4,) 1.0 False
[ 0.00135855  0.56871696 -0.08925147 -1.00857813] (4,) 1.0 False
[ 0.01273289  0.76490961 -0.10942303 -1.32790087] (4,) 1.0 False
[ 0.02803108  0.57132551 -0.13598105 -1.07136759] (4,) 1.0 False
[ 0.03945759  0.76795747 -0.1574084  -1.40344813] (4,) 1.0 False
[ 0.05481674  0.57510141 -0.18547736 -1.16382771] (4,) 1.0 False
[ 0.06631877  0.77208889 -0.20875391 -1.50845916] (4,) 1.0 False
[ 0.08176055  0.58001809 -0.2389231  -1.28753663] (4,) 1.0 True
[-0.0117385  -0.23178995  0.02932934  0.31812806] (4,) 1.0 False
[-0.0163743  -0.42731709  0.0356919   0.61991422] (4,) 1.0 False
[-0.02492065 -0.62291887  

In [2]:
####### Defining Model with 2 Neural Networks (Actor, Critic) ###########

def Model(input_shape, action_space, lr):
    input_layer = layers.Input(input_shape)
    hidden_layer = layers.Dense(units=512, activation="elu",kernel_initializer='he_uniform')
    action = layers.Dense(units=action_space,activation="softmax",kernel_initializer='he_uniform')
    value = layers.Dense(units=1,kernel_initializer='he_uniform')
    
    Actor = keras.Sequential(
       [input_layer,
        hidden_layer,
        action]
    )
    
    Critic = keras.Sequential(
       [input_layer,
        hidden_layer,
        value]
    )
    
    Actor.compile(loss="categorical_crossentropy", optimizer=RMSprop(lr=lr))
    Critic.compile(loss="mse", optimizer=RMSprop(lr=lr))
    
    return Actor, Critic
    

In [5]:
class A2CAgent:
    # Advantage Actor Critic Main Algorithm
    def __init__(self, env_name):
        # Initialization of Environment and Parameters 

        self.env_name = env_name       
        self.env = gym.make(env_name)
        self.action_size = self.env.action_space.n
        self.EPISODES, self.max_average = 10000, 0
        self.lr = 0.000025


        # Instantiate games and plot memory
        self.states, self.actions, self.rewards = [], [], []
        self.scores, self.episodes, self.average = [], [], []

        self.Save_Path = 'Models'
        self.state_size = (4,)
        
        if not os.path.exists(self.Save_Path): os.makedirs(self.Save_Path)
        self.path = '{}_A2C_{}'.format(self.env_name, self.lr)
        self.Model_name = os.path.join(self.Save_Path, self.path)

        # Create Actor-Critic network model
        self.Actor, self.Critic = Model(input_shape=self.state_size, action_space = self.action_size, lr=self.lr)
        
    def memorize(self, state, action, reward):
        # store episode actions to memory
        self.states.append(state)
        action_onehot = np.zeros([self.action_size])
        action_onehot[action] = 1
        self.actions.append(action_onehot)
        self.rewards.append(reward)
    
    def act(self, state):
        # Use the network to predict the next action to take, using the model
        prediction = self.Actor.predict(state)[0]
        action = np.random.choice(self.action_size, p=prediction)
        return action
    
    def comp_return(self, reward):
        # Compute the discounted return
        gamma = 0.99    # discount rate
        running_add = 0
        discounted_r = np.zeros_like(reward)
        for i in reversed(range(0,len(reward))):
            running_add = running_add * gamma + reward[i]
            discounted_r[i] = running_add
        discounted_r -= np.mean(discounted_r) # normalizing the result
        discounted_r /= np.std(discounted_r) # divide by standard deviation
        return discounted_r
 
    
    def train(self):
        # reshape memory to appropriate shape for training
        states = np.vstack(self.states)
        actions = np.vstack(self.actions)

        # Compute discounted return
        discounted_r = self.comp_return(self.rewards)

        # Get Critic network predictions
        values = self.Critic.predict(states)[:, 0]
        # Compute advantages
        advantages = discounted_r - values
        # training Actor and Critic networks
        self.Actor.fit(states, actions, sample_weight=advantages, epochs=1, verbose=0)
        self.Critic.fit(states, discounted_r, epochs=1, verbose=0)
        # reset training memory
        self.states, self.actions, self.rewards = [], [], []
        
    def load(self, Actor_name, Critic_name):
        self.Actor = load_model(Actor_name, compile=False)
        self.Critic = load_model(Critic_name, compile=False)
    
    def save(self):
        self.Actor.save(self.Model_name + '_Actor.h5')
        self.Critic.save(self.Model_name + '_Critic.h5')
    
    pylab.figure(figsize=(18, 9))
    
    def PlotModel(self, score, episode):
        self.scores.append(score)
        self.episodes.append(episode)
        self.average.append(sum(self.scores[-50:]) / len(self.scores[-50:]))
        if str(episode)[-2:] == "00":# much faster than episode % 100
            pylab.plot(self.episodes, self.scores, 'b')
            pylab.plot(self.episodes, self.average, 'r')
            pylab.ylabel('Score', fontsize=18)
            pylab.xlabel('Steps', fontsize=18)
            try:
                pylab.savefig(self.path+".png")
            except OSError:
                pass

        return self.average[-1]

    
    
    def step(self, action):
        next_state, reward, done, info = self.env.step(action)
        return next_state, reward, done, info
    
    def run(self):
        for e in range(self.EPISODES):
            state = self.env.reset()
            state = np.reshape(state, [1,4])
            done, score, SAVING = False, 0, ''
            while not done:
                #self.env.render()
                # Actor picks an action
                action = self.act(state)
                # Retrieve new state, reward, and whether the state is terminal
                next_state, reward, done, _ = self.step(action)
                # Memorize (state, action, reward) for training
                self.memorize(state, action, reward)
                # Update current state
                state = next_state
                state = np.reshape(state, [1,4])
                score += reward
                if done:
                    average = self.PlotModel(score, e)
                    # saving best models
                    if average >= self.max_average:
                        self.max_average = average
                        SAVING = "Improved Average"
                    else:
                        SAVING = ""
                    print("episode: {}/{}, score: {}, average: {:.2f} {}".format(e, self.EPISODES, score, average, SAVING), [None])
                    if average > 400:
                        self.save()
                    self.train()                 
        # close environemnt when finish training
        self.env.close()
        
    def test(self, Actor_name, Critic_name):
        self.load(Actor_name, Critic_name)
        for e in range(100):
            state = self.env.reset()
            state = np.reshape(state, [1,4])
            done = False
            score = 0
            while not done:
                self.env.render()
                action = np.argmax(self.Actor.predict(state))
                state, reward, done, _ = self.step(action)
                state = np.reshape(state, [1,4])
                score += reward
                if done:
                    print("episode: {}/{}, score: {}".format(e, self.EPISODES, score))
                    break
        self.env.close()


<Figure size 1296x648 with 0 Axes>

In [ ]:
if __name__ == "__main__":
    env_name = 'CartPole-v1'
    agent = A2CAgent(env_name)
    #agent.run()
    agent.test('CartPole-v1_A2C_2.5e-05_Actor.h5', 'CartPole-v1_A2C_2.5e-05_Actor.h5')


episode: 0/10000, score: 500.0
episode: 1/10000, score: 500.0
episode: 2/10000, score: 500.0
episode: 3/10000, score: 500.0
episode: 4/10000, score: 500.0
episode: 5/10000, score: 500.0
episode: 6/10000, score: 500.0
episode: 7/10000, score: 500.0
episode: 8/10000, score: 500.0
episode: 9/10000, score: 500.0
